stages:
  - Build
  - Build Docker
jobs:
- name: Yarn Install
  stage: Install
  image: node:14-alpine
  before_script:
  - yarn config set network-timeout 300000
  script:
  - yarn install
  - yarn build
  artifacts:
    paths:
      - .output
    expires_in: 3 days
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - node_modules
- name: Build docker with cmd args
  stage: Build
  workspace: none
  only:
    messages:
    - '[deploy]'
  except:
    events:
    - pull_request
  image: docker:stable
  services:
  - docker:stable-dind
  script:
    - docker ps -a
    - docker info
    - docker build -t my:docker .
    - docker images
    - sleep 10
